# Site settings
title: Sudarshan Patil - - Idealist, Deleoper and blogger.
description: Sudarshan patil 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sudarshan Patil
user_description: <!--br>Freelance embedded developer</br--> <br>Electronics project development, circuit designing, hardware customisation.</br> m:+91-989-092-1262 </br >e:contact@sudarshanpatil.com
user_title: Embedded developer.
email: p.sdrshn@gmail.com
twitter_username: sdrshnptl
github_username:  sdrshnptl
gplus_username:  sdrshnptl

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
